### ISSUE TITLE
入部リンクがTwitterのDMなのまずくね？

### ISSUE THREAD

**Issue by kakudo415** [kakudo415/RICORA_HP#6]
Twitterアカウント持ってない人を想定して、Google Formとか使ったほうがよさそう

**Comment by Shinonome517** [comment]
Twitterアカウントを持っていない人を想定するのは大賛成
普段の入部窓口という視点、及び新歓のときの入部窓口という視点それぞれから話しましょう。

**Comment by kakudo415** [comment]
RICORA Organizationのリポジトリに引き継ぎ。
